genesis:
  chain_id: "dhub-1"
  app_state:
    mint:
      params:
        mint_denom: "uhub"
    staking:
      params:
        bond_denom: "uhub"
    crisis:
      constant_fee:
        denom: "uhub"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: "uhub"
accounts:
  - name: alice
    coins: ["200000000uhub"]
  - name: bob
    coins: ["100000000uhub"]
validator:
  name: alice
  staked: "100000000uhub"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["100000uhub"]
