// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: oracle/join.proto

package types

import (
	fmt "fmt"
	secp256k1 "github.com/cosmos/cosmos-sdk/crypto/keys/secp256k1"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type JoinStatus int32

const (
	JOIN_STATUS_PENDING  JoinStatus = 0
	JOIN_STATUS_APPROVED JoinStatus = 1
	JOIN_STATUS_REJECTED JoinStatus = 2
)

var JoinStatus_name = map[int32]string{
	0: "JOIN_STATUS_PENDING",
	1: "JOIN_STATUS_APPROVED",
	2: "JOIN_STATUS_REJECTED",
}

var JoinStatus_value = map[string]int32{
	"JOIN_STATUS_PENDING":  0,
	"JOIN_STATUS_APPROVED": 1,
	"JOIN_STATUS_REJECTED": 2,
}

func (x JoinStatus) String() string {
	return proto.EnumName(JoinStatus_name, int32(x))
}

func (JoinStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_38ce7f22a4b4255f, []int{0}
}

type Join struct {
	ID              uint64            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OperatorAddress string            `protobuf:"bytes,2,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty"`
	EnclaveReport   []byte            `protobuf:"bytes,3,opt,name=enclave_report,json=enclaveReport,proto3" json:"enclave_report,omitempty"`
	EncPubKey       *secp256k1.PubKey `protobuf:"bytes,4,opt,name=enc_pub_key,json=encPubKey,proto3" json:"enc_pub_key,omitempty"`
	Status          JoinStatus        `protobuf:"varint,5,opt,name=status,proto3,enum=youngjoonlee.dhub.oracle.JoinStatus" json:"status,omitempty"`
}

func (m *Join) Reset()         { *m = Join{} }
func (m *Join) String() string { return proto.CompactTextString(m) }
func (*Join) ProtoMessage()    {}
func (*Join) Descriptor() ([]byte, []int) {
	return fileDescriptor_38ce7f22a4b4255f, []int{0}
}
func (m *Join) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Join) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Join.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Join) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Join.Merge(m, src)
}
func (m *Join) XXX_Size() int {
	return m.Size()
}
func (m *Join) XXX_DiscardUnknown() {
	xxx_messageInfo_Join.DiscardUnknown(m)
}

var xxx_messageInfo_Join proto.InternalMessageInfo

func (m *Join) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Join) GetOperatorAddress() string {
	if m != nil {
		return m.OperatorAddress
	}
	return ""
}

func (m *Join) GetEnclaveReport() []byte {
	if m != nil {
		return m.EnclaveReport
	}
	return nil
}

func (m *Join) GetEncPubKey() *secp256k1.PubKey {
	if m != nil {
		return m.EncPubKey
	}
	return nil
}

func (m *Join) GetStatus() JoinStatus {
	if m != nil {
		return m.Status
	}
	return JOIN_STATUS_PENDING
}

func init() {
	proto.RegisterEnum("youngjoonlee.dhub.oracle.JoinStatus", JoinStatus_name, JoinStatus_value)
	proto.RegisterType((*Join)(nil), "youngjoonlee.dhub.oracle.Join")
}

func init() { proto.RegisterFile("oracle/join.proto", fileDescriptor_38ce7f22a4b4255f) }

var fileDescriptor_38ce7f22a4b4255f = []byte{
	// 405 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x8a, 0xd3, 0x40,
	0x18, 0x80, 0x33, 0xb1, 0x16, 0x76, 0x56, 0xd7, 0x3a, 0x2e, 0x1a, 0x7a, 0xc8, 0x86, 0x45, 0x21,
	0x8a, 0xce, 0x60, 0x45, 0x4f, 0x82, 0x74, 0x6d, 0x94, 0x56, 0xe8, 0x96, 0x69, 0xf5, 0xe0, 0x25,
	0xa4, 0x93, 0x9f, 0x9a, 0x6d, 0x37, 0x7f, 0x98, 0x99, 0x88, 0x79, 0x03, 0x8f, 0xbe, 0x83, 0x2f,
	0xe3, 0x71, 0x8f, 0x9e, 0x44, 0xda, 0x07, 0xf0, 0x15, 0xa4, 0x4d, 0xad, 0x22, 0xec, 0xed, 0xe7,
	0xfb, 0xbf, 0xc0, 0x97, 0xf9, 0xe9, 0x4d, 0xd4, 0x89, 0x5a, 0x80, 0x38, 0xc3, 0x2c, 0xe7, 0x85,
	0x46, 0x8b, 0xcc, 0xab, 0xb0, 0xcc, 0x67, 0x67, 0x88, 0xf9, 0x02, 0x80, 0xa7, 0x1f, 0xca, 0x29,
	0xaf, 0xa5, 0xf6, 0xe1, 0x0c, 0x67, 0xb8, 0x91, 0xc4, 0x7a, 0xaa, 0xfd, 0xf6, 0xb1, 0x42, 0x73,
	0x8e, 0x46, 0x28, 0x5d, 0x15, 0x16, 0x85, 0x01, 0x55, 0x74, 0x9e, 0x3e, 0x9b, 0x3f, 0x16, 0x73,
	0xa8, 0x4c, 0xed, 0x1c, 0xff, 0x22, 0xb4, 0x31, 0xc0, 0x2c, 0x67, 0xb7, 0xa9, 0x9b, 0xa5, 0x1e,
	0x09, 0x48, 0xd8, 0x38, 0x69, 0x2e, 0x7f, 0x1c, 0xb9, 0xfd, 0x9e, 0x74, 0xb3, 0x94, 0xdd, 0xa7,
	0x2d, 0x2c, 0x40, 0x27, 0x16, 0x75, 0x9c, 0xa4, 0xa9, 0x06, 0x63, 0x3c, 0x37, 0x20, 0xe1, 0x9e,
	0xbc, 0xf1, 0x87, 0x77, 0x6b, 0xcc, 0xee, 0xd1, 0x03, 0xc8, 0xd5, 0x22, 0xf9, 0x08, 0xb1, 0x86,
	0x02, 0xb5, 0xf5, 0xae, 0x04, 0x24, 0xbc, 0x26, 0xaf, 0x6f, 0xa9, 0xdc, 0x40, 0xf6, 0x82, 0xee,
	0x43, 0xae, 0xe2, 0xa2, 0x9c, 0xc6, 0x73, 0xa8, 0xbc, 0x46, 0x40, 0xc2, 0xfd, 0xce, 0x11, 0xaf,
	0x63, 0x79, 0x1d, 0xcb, 0x77, 0xb1, 0x7c, 0x54, 0x4e, 0xdf, 0x40, 0x25, 0xf7, 0x20, 0x57, 0xf5,
	0xc8, 0x9e, 0xd3, 0xa6, 0xb1, 0x89, 0x2d, 0x8d, 0x77, 0x35, 0x20, 0xe1, 0x41, 0xe7, 0x2e, 0xbf,
	0xec, 0x61, 0xf8, 0xfa, 0xd7, 0xc6, 0x1b, 0x57, 0x6e, 0xbf, 0x79, 0x10, 0x53, 0xfa, 0x97, 0xb2,
	0x3b, 0xf4, 0xd6, 0xe0, 0xb4, 0x3f, 0x8c, 0xc7, 0x93, 0xee, 0xe4, 0xed, 0x38, 0x1e, 0x45, 0xc3,
	0x5e, 0x7f, 0xf8, 0xba, 0xe5, 0x30, 0x8f, 0x1e, 0xfe, 0xbb, 0xe8, 0x8e, 0x46, 0xf2, 0xf4, 0x5d,
	0xd4, 0x6b, 0x91, 0xff, 0x37, 0x32, 0x1a, 0x44, 0x2f, 0x27, 0x51, 0xaf, 0xe5, 0xb6, 0x1b, 0x9f,
	0xbf, 0xfa, 0xce, 0xc9, 0xab, 0x6f, 0x4b, 0x9f, 0x5c, 0x2c, 0x7d, 0xf2, 0x73, 0xe9, 0x93, 0x2f,
	0x2b, 0xdf, 0xb9, 0x58, 0xf9, 0xce, 0xf7, 0x95, 0xef, 0xbc, 0x7f, 0x38, 0xcb, 0xec, 0x3a, 0x4e,
	0xe1, 0xb9, 0xd8, 0x25, 0x3f, 0x5a, 0x00, 0x88, 0x75, 0xb3, 0xf8, 0x24, 0xb6, 0x37, 0xb7, 0x55,
	0x01, 0x66, 0xda, 0xdc, 0x5c, 0xe8, 0xc9, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8a, 0x78, 0x49,
	0x63, 0x0a, 0x02, 0x00, 0x00,
}

func (m *Join) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Join) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Join) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintJoin(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x28
	}
	if m.EncPubKey != nil {
		{
			size, err := m.EncPubKey.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintJoin(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.EnclaveReport) > 0 {
		i -= len(m.EnclaveReport)
		copy(dAtA[i:], m.EnclaveReport)
		i = encodeVarintJoin(dAtA, i, uint64(len(m.EnclaveReport)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.OperatorAddress) > 0 {
		i -= len(m.OperatorAddress)
		copy(dAtA[i:], m.OperatorAddress)
		i = encodeVarintJoin(dAtA, i, uint64(len(m.OperatorAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.ID != 0 {
		i = encodeVarintJoin(dAtA, i, uint64(m.ID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintJoin(dAtA []byte, offset int, v uint64) int {
	offset -= sovJoin(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Join) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ID != 0 {
		n += 1 + sovJoin(uint64(m.ID))
	}
	l = len(m.OperatorAddress)
	if l > 0 {
		n += 1 + l + sovJoin(uint64(l))
	}
	l = len(m.EnclaveReport)
	if l > 0 {
		n += 1 + l + sovJoin(uint64(l))
	}
	if m.EncPubKey != nil {
		l = m.EncPubKey.Size()
		n += 1 + l + sovJoin(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovJoin(uint64(m.Status))
	}
	return n
}

func sovJoin(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozJoin(x uint64) (n int) {
	return sovJoin(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Join) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowJoin
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Join: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Join: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJoin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthJoin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnclaveReport", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthJoin
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthJoin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EnclaveReport = append(m.EnclaveReport[:0], dAtA[iNdEx:postIndex]...)
			if m.EnclaveReport == nil {
				m.EnclaveReport = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncPubKey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthJoin
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthJoin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.EncPubKey == nil {
				m.EncPubKey = &secp256k1.PubKey{}
			}
			if err := m.EncPubKey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= JoinStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipJoin(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthJoin
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipJoin(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowJoin
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowJoin
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowJoin
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthJoin
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupJoin
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthJoin
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthJoin        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowJoin          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupJoin = fmt.Errorf("proto: unexpected end of group")
)
